project:
  type: book
  output-dir: docs
  resources: [.nojekyll]

book:
  title: "Reproducible Workflows"
  author: "Shilaan Alzahawi"
  date: "10/2/2023"
  chapters:
    - index.qmd
    - score-political.qmd
    - score-meta.qmd
    - score-criminology.qmd
    - score-education.qmd
    - management.qmd

#bibliography: 

format:
  html:
    theme: [united, custom.scss]
    toc-expand: true
    link-external-newwindow: true
    link-external-icon: true
    self-contained: false
    code-copy: true
    code-tools: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

#  pdf:
#    documentclass: scrreprt



